AY2122S2-CS2103-W16-2/tp

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/IndexedDeleteCommand.java
src/main/java/seedu/address/logic/commands/NamedDeleteCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java

Changes:
- Supports deletion by name (full name and capitalisation must match)
- Deletion by index is preserved
- Test cases are added accordingly
*Note: AB3 does not allow two persons with identical names*

Feature - Delete by name

---

docs/UserGuide.md

Descriptions added with examples:
- Newly added person will be placed at the top of the contacts' list
- The "find" command will match the keywords to all fields of a person, even if the keyword is incomplete
- Deletion can be by index or by name

Update UG for Add, Find, and Delete commands

---

docs/HelpGuide.md
docs/UserGuide.md
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/ui/ContactDetailCard.java
src/main/java/seedu/address/ui/ContactDetailPanel.java
src/main/java/seedu/address/ui/HelpWindow.java
src/main/java/seedu/address/ui/PersonCard.java

Changes include:
- Change javadocs comments
- Separate `UserGuide.md` into `HelpGuide.md` for `HelpWindow` and `UserGuide.md` for website

Final v1.2 branch

---

docs/UserGuide.md
src/main/resources/view/MainWindow.fxml

Changes:
- Updated the description for new features
- Numbered the commands for readability
- Removed unused formatting codes
- Changed window title to "uMessage"

Update UG and Change Window Title to "uMessage"

---

src/main/java/seedu/address/MainApp.java

This PR bumps internal version number for v1.3 release

Bump version for 1.3 trial release

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/person/UniquePersonListTest.java
src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
src/test/java/seedu/address/testutil/AddressBookBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

This PR fixes #120 
Changes:
- The full list is displayed alphabetically
- Tests are updated accordingly, but no new test cases added

List Sequence Alphabetical

---

src/main/resources/view/ContactDetailCard.fxml

Update GUI - Alter contact detail card width to fit email label and value.

---

src/main/java/seedu/address/ui/ContactDetailCard.java
src/main/resources/view/ContactDetailCard.fxml
src/main/resources/view/LightTheme.css

Feature - Change Labels to TextArea to make fields copy friendly

---

src/main/java/seedu/address/model/ClipboardManager.java
src/main/java/seedu/address/model/socialmedia/SocialMedia.java
src/main/java/seedu/address/ui/ContactDetailCard.java
src/main/resources/view/ContactDetailCard.fxml

Creates links to emails and telegram for convenience ease of communication.
#138

Feature - Email and Telegram links and make fields copy friendly

---

src/main/resources/view/LightTheme.css
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/PersonListPanel.fxml

Fix css of ListCell and ListView

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/assets/HelpGuide.md

To ensure the helpguide gets bundled in the `addressbook.jar`

Move helpguide into resource folder

---

docs/DeveloperGuide.md

My update to DG in week 10 was not recognised because someone modified the lines later (removing trailing spaces) :frowning_face:
PR in week 10 [here](https://github.com/AY2122S2-CS2103-W16-2/tp/pull/124/commits)

Claim DG use cases written by me

---

src/main/java/seedu/address/ui/ContactDetailCard.java
src/main/resources/view/ContactDetailCard.fxml
src/main/resources/view/LightTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/MeetingCard.fxml

Solves #166 and addresses #185

Ui Updates : TagPanel and ContactCard

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TagCard.java
src/main/java/seedu/address/ui/TagPanel.java

This PR fixes #214 
Changes:
Included a `clickTag` method in `MainWindow` and `Logic`. The method updates both `ResultDisplay`s in the `mainWindow`

Update ResultDisplay for both Contacts and Meetings when a tag is clicked

---

docs/DeveloperGuide.md

My last claim didn't work, so I try claiming small blocks :((

Claim DG lines written by me 2

---

docs/DeveloperGuide.md

I used the wrong comment format previously :(

Claim DG lines written by me 3

---

src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/tag/UniqueTagList.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

Addresses Issue #241
Fixes the method `UniqueTagList#setEmergencyContactTag`

Fix emergency contact tag

---

src/main/java/seedu/address/ui/ContactDetailPanel.java
src/main/java/seedu/address/ui/MainWindow.java

Update ResultDisplay when a person is clicked

---

docs/team/kavxya.md

Add PPP details to kavxya.md in the team docs.

PPP (kavxya) 

---

docs/UserGuide.md

Address Issue #160, #183 and #162. 
The changes are as follows:
- Add short description about Global Tags
- Add Link to the downloadable jar file under the 'Quick Start' section

Update errors in UG

---

src/main/java/seedu/address/logic/commands/add/AddSocialsToPersonCommand.java
src/main/java/seedu/address/logic/commands/delete/DeletePersonCommand.java
src/main/java/seedu/address/logic/commands/delete/DeletePersonsSocialCommand.java
src/main/java/seedu/address/logic/commands/delete/DeletePersonsTagCommand.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/socialmedia/PlatformDescription.java
src/main/java/seedu/address/model/socialmedia/PlatformName.java
src/test/java/seedu/address/logic/commands/add/AddTagOnlyCommandTest.java
src/test/java/seedu/address/logic/commands/delete/DeletePersonsTagCommandTest.java
src/test/java/seedu/address/logic/commands/delete/DeleteTagOnlyCommandTest.java

Bug fixing

---

src/main/java/seedu/address/logic/commands/meetingcommands/AddTagToMeetingCommand.java
src/main/java/seedu/address/logic/commands/meetingcommands/DeleteMeetingsTagCommand.java
src/test/java/seedu/address/logic/commands/meetingcommands/AddTagToMeetingCommandTest.java
src/test/java/seedu/address/logic/commands/meetingcommands/DeleteMeetingTagCommandTest.java
src/test/java/seedu/address/testutil/TypicalTags.java

Added test cases for `AddTagToMeetingCommand` and `DeleteMeetingsTagCommand`.

Increase test coverage for meetings

---

docs/team/zihaowrez.md

Update PPP zihaowrez

---

docs/team/cheehongw.md

Update PPP (Chee Hong)

---

docs/UserGuide.md

Preview here: 
https://cheehongw.github.io/tp/UserGuide.html
Right click -> `print`

UG: Page breaks
